# Generated by Django 4.2.2 on 2023-06-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microorganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=250)),
                ('characteristics', models.TextField(max_length=1000)),
                ('description', models.TextField(max_length=1000)),
                ('manifestation', models.TextField(max_length=1000)),
                ('laboratory_diagnosis', models.TextField(max_length=1000)),
                ('verified_microorganism', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
